apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: webhook
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webhook
  template:
    metadata:
      labels:
        name: webhook
    spec:
      containers:
        - name: webhook
          imagePullPolicy: Always
          image: 'ghcr.io/krateoplatformops/webhook:latest'
          envFrom:
            - configMapRef:
                name: webhook-config
          env:
            - name: PORT
              value: '8080'
            - name: LOG_LEVEL
              value: 'info'
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: '128Mi'
              cpu: '100m'
      imagePullSecrets:
        - name: cr-token
      restartPolicy: Always
